### ISSUE TITLE
Public access to `enabled` map

### ISSUE THREAD

**Issue by cathalgarvey** [azer/logger#3]
Hey, this logger looks great- a good blend of simple API, levelling/app-segregation, and nice design.

One feature I'd really like, though, is the ability to programmatically enable logs and log levels, rather than relying on the environment variable method. If I'm already defining a CLI interface for my application I'd prefer to add a "-v" / "-vv" flag to enable various log levels or log types.

It looks like this would be easy to do if the "enabled" map were exposed publicly. Alternatively, if a setter function were added to complement `IsEnabled`, so you could call a function with a logger name and a state to enable. Something like `SetEnabled(logname string, setstate bool) error`.

I can write it up and PR, if you like?

**Comment by azer** [comment]
@cathalgarvey thanks @cathalgarvey! would be great if you can send a PR

**Comment by cathalgarvey** [comment]
Cool, will do! :)
